### ISSUE TITLE
allow serialisation/deserialisation of *Err

### ISSUE THREAD

**Issue by JavierZunzunegui** [juju/errors#27]
I want juju errors to cross RPC boundaries and to do that I need some methods to serialize them on one side, and to recreate the error on the other from its serialized form. Can't do that now as all inputs are private, particularly 'file' and 'line' can only be set by SetLocation (and therefore using runtime.Caller values only), while I need them initialized to arbitrary values.

I have working code (and tests) for this, let me know if a PR is welcome or any concerns you may have about such changes.

**Comment by anastasiamac** [comment]
PRs are welcome \o/

**Comment by JavierZunzunegui** [comment]
Clsoing, not sure why I didn't send the above PR changes but either way it is now way too old and irrelevant.
