### ISSUE TITLE
mgo dependency?

### ISSUE THREAD

**Issue by karnauskas** [juju/errors#41]
`go mod` is picking up dependencies which are not used anywhere in the code. 

eg following: 
```
gopkg.in/mgo.v2
```

**Comment by takeda** [comment]
`go mod why` is showing me this:

```github.com/juju/errors
github.com/juju/errors.test
github.com/juju/testing/checkers
gopkg.in/mgo.v2/bson```

**Comment by karnauskas** [comment]
It's defined in here https://github.com/juju/errors/blob/master/dependencies.tsv#L4 Why?

**Comment by howbazaar** [comment]
I think it is a transitive dependency due to some of the testing helpers from juju/testing.
