### ISSUE TITLE
Support go errors.Is(...), errors.As(...), implement error.Unwrap()

### ISSUE THREAD

**Issue by Frug** [juju/errors#47]
I use juju as a drop-in replacement for the base "errors" package. In all cases until now I could just swap out the import line and not worry about it, however with the addition of errors.Is and errors.As I've had to separately import the old errors package to keep those functions.

Can juju get .Is and .As aliases for the regular error package versions, and add a .Unwrap method to its errors?

I think the first two are trivial, but I believe .Unwrap is supposed to return the immediate parent, so it's not quite the same as juju's .Cause. 

If this is reasonable I can make a PR.

**Comment by tlm** [comment]
@Frug this is an old issue now so sorry for the late reply. I definitely think this is something we want to support specifically for the errors produced from this package to be compatible with the new API. I am not sure how we feel implementing or proxying direct features like the above through the package. I will do some research and get back to you on what a decent design might look like.

**Comment by barrettj12** [comment]
@Frug happy to say we've done this now (16 months later, sorry), so you can continue using juju/errors as a drop-in replacement for the standard errors package.

**Comment by WinChua** [comment]
It seems that the implementation of .Unwrap is not so reasonable. Currently the impletement is 
```
func (e *Err) Unwrap() error {
    return e.previous
}
```
While, consider for this cituation, 
```
// dao.go
func GetData() (string, error) {
    if data, err := redis.Get("HELLLO"); err == nil {
          return data, nil
    } else if errors.Is(err, redis.ErrNil) {
          return "", errors.Wrapf(err, errors.NotFoundf("GET KEY[%s]", "HELLO"))
    } 
}
// impl.go
data, e := dao.GetData()
if errors.Is(e, errors.NotFound) { // it's false now, because the use of Wrapf in GetData
     // some logic
}
```
I should use `errors.Is(errors.Cause(e), errors.NotFound)` instead.
It seem not so compatity with the std errors
